doxygen pygoogle-common-config.dox
doxygen pygoogle-indexer-config.dox
doxygen pygoogle-crawler-config.dox
doxygen pygoogle-webui-config.dox
doxygen pygoogle-test-config.dox
cd Common/latex
make pdf
cd ../Crawler/latex
make pdf
cd ../Indexer/latex
make pdf
cd ../WebUI/latex
make pdf
cd ../Test/latex
make pdf